version: '3.8'

services:
  spark-master:
    image: bitnami/spark:${SPARK_VERSION}
    container_name: spark-master
    env_file:
      - variables.env  # Загружаем переменные окружения
    ports:
      - "8080:8080"  # Веб-интерфейс Master
      - "7077:7077"  # Порт для подключения Worker
    volumes:
      - ./src:/app

  spark-worker:
    image: bitnami/spark:${SPARK_VERSION}
    container_name: spark-worker
    env_file:
      - variables.env  # Загружаем переменные окружения
    depends_on:
      - spark-master
    ports:
      - "8081:8081"  # Веб-интерфейс Worker
    volumes:
      - ./src:/app