version: '3.8'

services:
  spark:
    image: bitnami/spark:${SPARK_VERSION}
    container_name: spark-standalone
    env_file:
      - variables.env  # Загружаем переменные окружения
    ports:
      - "8080:8080"  # Веб-интерфейс Spark
    volumes:
      - ./src:/app
    command: ["spark-submit", "--master", "local[*]", "/app/main.py"]